/*
 * generated by Xtext 2.19.0
 */
package com.xatkit.language.common.ide


/**
 * Use this class to register ide components.
 */
class CommonIdeModule extends AbstractCommonIdeModule {
}
