/*
 * generated by Xtext 2.12.0
 */
package com.xatkit.language.execution

import org.apache.log4j.Logger
import org.eclipse.xtext.common.types.access.impl.DeclaredTypeFactory
import org.apache.log4j.Level

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ExecutionStandaloneSetup extends ExecutionStandaloneSetupGenerated {

	def static void doSetup() {
		new ExecutionStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
