/*
 * generated by Xtext 2.15.0
 */
package com.xatkit.language.execution.ide


/**
 * Use this class to register ide components.
 */
class ExecutionIdeModule extends AbstractExecutionIdeModule {
}
