/*
 * generated by Xtext 2.15.0
 */
package com.xatkit.language.platform.ide


/**
 * Use this class to register ide components.
 */
class PlatformIdeModule extends AbstractPlatformIdeModule {
}
