/*
 * generated by Xtext 2.12.0
 */
package com.xatkit.language.intent

import com.xatkit.language.intent.generator.IntentGenerator

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class IntentRuntimeModule extends AbstractIntentRuntimeModule {
	
	override bindILinkingService() {
		return IntentLinkingService
	}
	
	override bindILinker() {
		IntentLazyLinker
	}
	
	override bindIGenerator() {
		return IntentGenerator
	}
	
}
