/*
 * generated by Xtext 2.15.0
 */
package com.xatkit.language.common.ui.quickfix

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
class CommonQuickfixProvider extends DefaultQuickfixProvider {

}
